"""empty message

Revision ID: e99832b03824
Revises: 9cc15f2c5b4c
Create Date: 2025-03-16 09:50:25.493526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99832b03824'
down_revision: Union[str, None] = '9cc15f2c5b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('reply_if_correct', sa.Text(), nullable=False),
    sa.Column('reply_if_wrong', sa.Text(), nullable=False),
    sa.Column('is_true', sa.Boolean(), nullable=False),
    sa.Column('misinformation_level_delta', sa.Integer(), nullable=False),
    sa.Column('pollution_delta', sa.Integer(), nullable=False),
    sa.Column('trust_science_delta', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('misinformation_level', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('pollution', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('trust_science', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('history', sa.JSON(), nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('users', 'history')
    op.drop_column('users', 'trust_science')
    op.drop_column('users', 'pollution')
    op.drop_column('users', 'misinformation_level')
    op.drop_table('news')
    # ### end Alembic commands ###
