import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { QueryClientProvider } from "./query-client-provider";
import localFont from "next/font/local";

const homeVideo = localFont({
  src: [
    {
      path: "../../public/fonts/Pixelated.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-pixelated-regular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${homeVideo.variable} antialiased`}>
        <Toaster />
        <QueryClientProvider>{children}</QueryClientProvider>
      </body>
    </html>
  );
}
